return {
    { "ribru17/bamboo.nvim",                lazy = true },
    { "Shatur/neovim-ayu",                  lazy = true },
    { "catppuccin/nvim",                    name = "catppuccin", lazy = true },
    { "ellisonleao/gruvbox.nvim",           lazy = true },
    { "rebelot/kanagawa.nvim",              lazy = true },
    { "loctvl842/monokai-pro.nvim",         lazy = true },
    { "folke/tokyonight.nvim",              lazy = true },
    { "sainnhe/everforest",                 lazy = true },
    { "rose-pine/neovim",                   name = "rose-pine", lazy = true },
    { "EdenEast/nightfox.nvim",             lazy = true },
    { "projekt0n/github-nvim-theme",        lazy = true },
    { "sainnhe/gruvbox-material",           lazy = true },
    { "sainnhe/sonokai",                    lazy = true },
    { "bluz71/vim-moonfly-colors",          name = "moonfly", lazy = true },
    { "bluz71/vim-nightfly-colors",         name = "nightfly", lazy = true },
    { "maxmx03/solarized.nvim",             lazy = true },
    { "craftzdog/solarized-osaka.nvim",     lazy = true },
    { "neanias/everforest-nvim",            lazy = true },
}
